#Port
server:
  port: 9090
#Database connection
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        
  datasource:
    url: jdbc:mysql://localhost:3306/blogservice
    username: root
    password: root
   